draw_config:
  dark_mode: auto
  separate_combo_diagrams: false

parse_config:
  raw_binding_map:
    "&sys_reset": Reset
    "&bootloader": Boot
    "&swapper": Win Next
    "&caps_word": Caps Word
    "&inv_qm": Â¿

    "&kp LC(LG(LEFT))": Desk Left
    "&kp LC(LG(RIGHT))": Desk Right
    "&kp LC(TAB)": Tab Right
    "&kp LC(LS(TAB))": Tab Left
    "&kp LA(F4)": Win Close
    "&kp LC(F4)": Tab Close
    "&kp LS(TAB)": Win Prev
    "&kp LS(INS)": Paste
    "&kp LG(L)": Lock

    "&out OUT_USB": Out USB
    "&out OUT_BLE": Out BLE

    "&bt BT_SEL 0": BT 1
    "&bt BT_SEL 1": BT 2
    "&bt BT_SEL 2": BT 3
    "&bt BT_SEL 3": BT 4
    "&bt BT_SEL 4": BT 5

    "&mmv MOVE_UP": Mouse â†‘
    "&mmv MOVE_DOWN": Mouse â†“
    "&mmv MOVE_LEFT": Mouse â†
    "&mmv MOVE_RIGHT": Mouse â†’

    "&msc SCRL_UP": Scroll â†‘
    "&msc SCRL_DOWN": Scroll â†“
    "&msc SCRL_LEFT": Scroll â†
    "&msc SCRL_RIGHT": Scroll â†’

    "&mkp LCLK": Left Click
    "&mkp RCLK": Right Click
    "&mkp MCLK": Middle Click
    "&mkp MB4": Back Click
    "&mkp MB5": Forward Click

  zmk_keycode_map:
    C_VOL_UP: ðŸ”Š
    C_VOL_DN: ðŸ”‰
    C_MUTE: ðŸ”‡
    C_AL_CALC: Calc

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: â£
    BSPC: âŒ«
    RET: âŽ
    TAB: â†¹
    DEL: âŒ¦

    PG_UP: Page Up
    PG_DN: Page Down
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: â†‘
    DOWN: â†“
    LEFT: â†
    RIGHT: â†’

    C_PP: â¯ # Play Pause
    C_NEXT: â­ï¸
    C_PREV: â®ï¸

    # defaults
    AMPERSAND: "&"
    AMPS: "&"
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: "*"
    ASTRK: "*"
    AT: "@"
    AT_SIGN: "@"
    BACKSLASH: "\""
    BSLH: "\""
    CARET: "^"
    COLON: ":"
    COMMA: ","
    DLLR: "$"
    DOLLAR: "$"
    DOT: "."
    DOUBLE_QUOTES: "\""
    DQT: "\""
    EQUAL: "="
    EXCL: "!"
    EXCLAMATION: "!"
    FSLH: "/"
    GRAVE: "`"
    GREATER_THAN: ">"
    GT: ">"
    HASH: "#"
    LBKT: "["
    LBRC: "{"
    LEFT_BRACE: "{"
    LEFT_BRACKET: "["
    LEFT_PARENTHESIS: "("
    LESS_THAN: "<"
    LPAR: "("
    LT: "<"
    MINUS: "-"
    NON_US_BACKSLASH: "\\"
    NON_US_BSLH: "|"
    NON_US_HASH: "#"
    NUHS: "#"
    PERCENT: "%"
    PERIOD: "."
    PIPE: "|"
    PIPE2: "|"
    PLUS: "+"
    POUND: "#"
    PRCNT: "%"
    QMARK: "?"
    QUESTION: "?"
    RBKT: "]"
    RBRC: "}"
    RIGHT_BRACE: "}"
    RIGHT_BRACKET: "]"
    RIGHT_PARENTHESIS: ")"
    RPAR: ")"
    SEMI: ";"
    SEMICOLON: ";"
    SINGLE_QUOTE: "''"
    SLASH: "/"
    SQT: "''"
    STAR: "*"
    TILDE: "~"
    TILDE2: "~"
    UNDER: "_"
    UNDERSCORE: "_"
    LAQUO": "Â«"
    RAQUO": "Â»"

  zmk_combos:
    combo_lang_ru:
      draw_separate: true
    combo_lang_en:
      draw_separate: true
