manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: urob
    url-base: https://github.com/urob
  - name: caksoylar
    url-base: https://github.com/caksoylar
  - name: janpfischer
    url-base: https://github.com/janpfischer
  - name: carrefinho
    url-base: https://github.com/carrefinho
  - name: ilyasshafigin
    url-base: https://github.com/ilyasshafigin
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: zmk-helpers
    remote: urob
    revision: main
    path: modules/zmk/helpers
  - name: zmk-smart-toggle
    remote: caksoylar
    revision: main
    path: modules/zmk/smart-toggle
  - name: prospector-zmk-module
    remote: carrefinho
    #revision: main
    revision: core/zephyr-4-1
    path: modules/zmk/prospector
  - name: zmk-dongle-screen
    #remote: janpfischer
    remote: ilyasshafigin
    revision: main
    path: modules/zmk/dongle-screen
  self:
    path: config
