manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: badjeff
    url-base: https://github.com/badjeff
  - name: caksoylar
    url-base: https://github.com/caksoylar
  - name: carrefinho
    url-base: https://github.com/carrefinho
  - name: janpfischer
    url-base: https://github.com/janpfischer
  - name: urob
    url-base: https://github.com/urob
  projects:
  - name: zmk
    remote: zmkfirmware
    revision: main
    import: app/west.yml
  - name: zmk-helpers
    remote: urob
    revision: main
    path: modules/zmk/helpers
  - name: zmk-smart-toggle
    remote: caksoylar
    revision: main
    path: modules/zmk/smart-toggle
  - name: prospector-zmk-module
    remote: carrefinho
    #revision: main
    revision: core/zephyr-4-1
    path: modules/zmk/prospector
  # - name: zmk-dongle-screen
    # remote: janpfischer
    # revision: main
    # path: modules/zmk/dongle-screen
  - name: zmk-pmw3610-driver
    remote: badjeff
    revision: zmk-0.4
    path: modules/zmk/pmw3610-driver
  - name: zmk-trackball-arrows
    path: modules/local/zmk-trackball-arrows
    url: file:///workspace/modules/local/zmk-trackball-arrows
  self:
    path: config
