manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: badjeff
    url-base: https://github.com/badjeff
  - name: caksoylar
    url-base: https://github.com/caksoylar
  - name: carrefinho
    url-base: https://github.com/carrefinho
  - name: englmaxi
    url-base: https://github.com/englmaxi
  - name: janpfischer
    url-base: https://github.com/janpfischer
  - name: kot149
    url-base: https://github.com/kot149
  - name: oleksandrmaslov
    url-base: https://github.com/oleksandrmaslov
  - name: urob
    url-base: https://github.com/urob
  - name: zettaface
    url-base: https://github.com/zettaface
  projects:
  # ZMK
  - name: zmk
    remote: zmkfirmware
    #revision: main
    # for fix error in prospector module: implicit declaration of function 'zmk_endpoints_selected'
    revision: ac7f75b8591d39aaf3b66b9d26f26c9ed921a009
    import: app/west.yml

  # Helper
  - name: zmk-helpers
    remote: urob
    revision: main
    path: modules/zmk/helpers

  # Driver
  - name: zmk-pmw3610-driver
    remote: badjeff
    revision: zmk-0.4
    path: modules/zmk/pmw3610-driver

  # Behavior & Input processor
  - name: zmk-smart-toggle
    remote: caksoylar
    revision: main
    path: modules/zmk/smart-toggle
  - name: zmk-input-processor-keybind
    remote: zettaface
    revision: main
    path: modules/zmk/input-processor-keybind
  - name: zmk-pointing-acceleration
    remote: oleksandrmaslov
    revision: main
    path: modules/zmk/pointing-acceleration
  - name: zmk-scroll-snap
    remote: kot149
    revision: v1
    path: modules/zmk/scroll-snap

  # Dongle
  - name: prospector-zmk-module
    remote: carrefinho
    revision: feat/new-status-screens #main
    path: modules/zmk/prospector
  - name: zmk-dongle-display
    remote: englmaxi
    #revision: main
    # for fix error in prospector module: implicit declaration of function 'zmk_endpoints_selected'
    revision: 9f0f0bf3107ff976e696a01c169fdd076c2874aa
    path: modules/zmk/dongle-display
  # - name: zmk-dongle-screen
    # remote: janpfischer
    # revision: main
    # path: modules/zmk/dongle-screen
  self:
    path: config
