name: Compile ZMK
on:
  workflow_dispatch:
  push:
    paths:
    - "config/*.keymap"
    - "config/*.dtsi"
    - "config/boards/*/*/*.conf"
    - "config/boards/*/*/*.overlay"
    - "config/boards/*/*/*.keymap"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
