# Draw keymap diagrams using keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch:
  # push:
  #   paths:
  #   - "config/*.keymap"
  #   - "config/*.dtsi"
  #   - "config/*/*.dtsi"
  #   - "boards/*/*/*.dtsi"
  #   - "keymap-drawer/config.yaml"
  #   - ".github/workflows/draw-keymaps.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      install_branch: main
      keymap_patterns: "config/*.keymap"
      config_path: "config/keymap-drawer.yaml"
      output_folder: "keymap-drawer"
      commit_message: "Update keymap"
      fail_on_error: true
